import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { callLlmChat, parseWebVtt, vttToDataUrl } from "../lib/ai-subtitles";
import { useAiSubtitlesStore } from "../stores/ai-subtitles-store";
import type { SubtitleItem } from "../types/api";
import type { VideoStream } from "../types/stream";

type Props = {
  isOpen: boolean;
  onClose: () => void;
  stream: VideoStream;
  onApplySubtitle?: (sub: SubtitleItem) => void;
  onToast?: (msg: string) => void;
};

export function AiSubtitlesModal({ isOpen, onClose, stream, onApplySubtitle, onToast }: Props) {
  const { endpoint, apiKey, model, targetLanguage, cachedTracks, cacheTrack } =
    useAiSubtitlesStore();

  const cached = cachedTracks[stream.id];
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!isOpen) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.body.style.overflow = prev;
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  async function handleGenerate() {
    if (!endpoint) {
      setError("请先在设置中配置 API Endpoint 端点");
      return;
    }
    setGenerating(true);
    setError(null);

    try {
      // Build prompt for LLM
      const nativeSubtitle = stream.subtitles?.[0];
      let rawTextContext = "";

      if (nativeSubtitle?.url) {
        try {
          const res = await fetch(nativeSubtitle.url);
          if (res.ok) {
            rawTextContext = await res.text();
          }
        } catch {
          // Fall back to title/description
        }
      }

      const promptMessages = [
        {
          role: "system",
          content:
            "You are a professional video subtitle translator. Output strictly valid WebVTT format starting with 'WEBVTT'. Do not include markdown codeblocks or conversational text.",
        },
        {
          role: "user",
          content: rawTextContext
            ? `Translate and align the following video subtitles into ${targetLanguage}:\n\n${rawTextContext.slice(0, 3000)}`
            : `Generate realistic and helpful bilingual commentary subtitles for a video titled "${stream.title}" by ${stream.channelName} with duration ${Math.round(stream.duration)} seconds in ${targetLanguage}. Output valid WebVTT format starting with WEBVTT with timestamps covering key moments of the video.`,
        },
      ];

      const completion = await callLlmChat(endpoint, apiKey, model, promptMessages);
      let vttContent = completion.trim();
      if (vttContent.startsWith("```")) {
        vttContent = vttContent.replace(/^```[a-z]*\n/, "").replace(/\n```$/, "");
      }
      if (!vttContent.startsWith("WEBVTT")) {
        vttContent = `WEBVTT\n\n${vttContent}`;
      }

      const track = {
        vtt: vttContent,
        languageTag: `${targetLanguage}-AI`,
        displayLanguageName: `✨ AI 字幕 (${targetLanguage})`,
        generatedAt: Date.now(),
      };

      cacheTrack(stream.id, track);

      // Mount into player
      const subItem: SubtitleItem = {
        url: vttToDataUrl(vttContent),
        mimeType: "text/vtt",
        languageTag: track.languageTag,
        displayLanguageName: track.displayLanguageName,
        isAutoGenerated: true,
      };
      onApplySubtitle?.(subItem);
      onToast?.("✨ AI 字幕生成成功并已应用到播放器！");
      onClose();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      setError(`生成失败: ${msg}`);
    } finally {
      setGenerating(false);
    }
  }

  function handleApplyCached() {
    if (!cached) return;
    const subItem: SubtitleItem = {
      url: vttToDataUrl(cached.vtt),
      mimeType: "text/vtt",
      languageTag: cached.languageTag,
      displayLanguageName: cached.displayLanguageName,
      isAutoGenerated: true,
    };
    onApplySubtitle?.(subItem);
    onToast?.("已加载缓存的 AI 字幕");
    onClose();
  }

  const cues = cached ? parseWebVtt(cached.vtt) : [];

  return createPortal(
    <>
      <div
        role="none"
        className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="ai-subtitles-modal-title"
        className="fixed z-50 left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[540px] max-w-[calc(100vw-2rem)] max-h-[90vh] overflow-y-auto bg-surface border border-border-strong rounded-2xl shadow-2xl p-6 flex flex-col gap-5 text-fg [scrollbar-width:thin]"
      >
        <div className="flex items-center justify-between pb-3 border-b border-border-strong/60">
          <div className="flex items-center gap-2.5">
            <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-indigo-500/15 text-indigo-400 font-bold text-base">
              ✨
            </span>
            <div>
              <h2 id="ai-subtitles-modal-title" className="text-base font-semibold leading-tight">
                AI 智能字幕 (LLM Subtitles)
              </h2>
              <p className="text-xs text-fg-soft mt-0.5">
                使用自定义大语言模型为哔哩哔哩及其他视频生成高精度双语字幕
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-fg-muted hover:text-fg text-sm px-2 py-1 rounded-md transition-colors"
          >
            ✕
          </button>
        </div>

        <div className="flex items-center justify-between p-3 rounded-xl bg-surface-strong border border-border-strong text-xs">
          <div className="flex flex-col gap-0.5">
            <span className="text-fg-muted">当前 LLM 模型配置:</span>
            <span className="font-mono text-fg font-medium">
              {model} · {targetLanguage.toUpperCase()} ·{" "}
              {endpoint.replace(/^https?:\/\//, "").slice(0, 25)}
            </span>
          </div>
          <a
            href="/settings?section=ai"
            className="px-2.5 py-1 text-xs text-accent hover:underline border border-accent/30 rounded-lg transition-colors"
          >
            更改配置
          </a>
        </div>

        {cached ? (
          <div className="flex flex-col gap-3 p-4 rounded-xl border border-indigo-500/30 bg-indigo-500/5">
            <div className="flex items-center justify-between">
              <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[11px] font-medium bg-indigo-500/20 text-indigo-400">
                ● 已生成 AI 字幕 ({cues.length} 句)
              </span>
              <span className="text-xs text-fg-soft font-mono">
                {new Date(cached.generatedAt).toLocaleDateString()}
              </span>
            </div>

            <div className="max-h-36 overflow-y-auto pr-1 flex flex-col gap-1.5 text-xs text-fg-soft font-mono bg-surface-strong/60 p-2.5 rounded-lg border border-border-strong/40">
              {cues.slice(0, 6).map((cue) => (
                <div key={`${cue.startSeconds}-${cue.endSeconds}`} className="flex gap-2">
                  <span className="text-indigo-400 shrink-0">{Math.round(cue.startSeconds)}s:</span>
                  <span className="text-fg truncate">{cue.text}</span>
                </div>
              ))}
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-border-strong/40">
              <button
                type="button"
                onClick={handleGenerate}
                disabled={generating}
                className="px-3 py-1.5 text-xs text-fg-muted hover:text-fg border border-border-strong rounded-lg transition-colors disabled:opacity-50"
              >
                {generating ? "重新生成中..." : "重新生成"}
              </button>
              <button
                type="button"
                onClick={handleApplyCached}
                className="px-4 py-1.5 text-xs font-medium bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors"
              >
                应用到播放器
              </button>
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-2 p-4 rounded-xl border border-border-strong bg-surface-strong/30 text-xs text-fg-muted">
              <p>
                💡 点击下方按钮，系统将调用配置的 LLM 模型分析视频元数据及字幕流，生成标准的 WebVTT
                双语智能字幕。
              </p>
              <p className="text-[11px] text-fg-soft">
                生成后的字幕可在 Vidstack 播放器底部的「字幕」菜单中随时选择或切换显示样式。
              </p>
            </div>

            <button
              type="button"
              onClick={handleGenerate}
              disabled={generating}
              className="w-full py-2.5 text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {generating ? "正在调用 LLM 生成字幕..." : "✨ 一键生成 AI 智能字幕"}
            </button>
          </div>
        )}

        {error && (
          <div className="p-3 rounded-lg text-xs bg-danger/10 text-danger border border-danger/30">
            {error}
          </div>
        )}
      </div>
    </>,
    document.body,
  );
}
